---
# - debug: var=ansible_distribution
# - debug: var=ansible_distribution_release

- name: load os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_release}}.yaml"
      - "{{ ansible_distribution }}.yaml"
      - "{{ ansible_os_family }}.yaml"


# - debug: var=fluentd_install_script

- name: make sure td-agent user is created
  become: true
  user:
    name: td-agent
    state: present

- name: get install script
  become: true
  get_url:
    url: "{{ fluentd_install_url }}/{{ fluentd_install_script }}"
    dest: "{{ fluentd_temp_dir }}/{{ fluentd_install_script }}"

- name: run treasuredata install script
  become: true
  command: "sh {{ fluentd_temp_dir }}/{{ fluentd_install_script }}"

- name: create spool directory
  become: true
  file:
    dest: "{{ fluentd_spool_dir }}"
    state: directory
    owner: td-agent
    group: td-agent
    mode: 0755

- name: create config directory
  become: true
  file:
    dest: "{{ fluentd_conf_dir }}"
    state: directory
    group: td-agent
    mode: 0755

- name: install requirements for plugin compilation
  become: true
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: "{{ fluentd_plugin_required_packages }}"


- name: install fluentd plugins
  become: true
  command: "{{ fluentd_bin_gem_cmd }} install -N fluent-plugin-{{ item }}"
  with_items: "{{fluentd_plugins}}"
  when: fluentd_plugins is not none and fluentd_plugins|length > 0


- name: install td-agent configuration
  become: true
  template:
    src: etc_td-agent_td-agent.conf
    dest: "{{ fluentd_conf_file }}"
    owner: td-agent
    group: td-agent
    mode: 0644
  when: fluentd_sources is defined or fluentd_matches is defined
